### ISSUE TITLE
ReaderError: unacceptable character #x0082: special characters are not allowed

### ISSUE THREAD

**Issue by maneeshjain1982** [invoice-x/invoice2data#168]
mj@DeskTop-System:~/pdf_to_text/invoice2data$ invoice2data --input-read pdftotext oyo.pdf
I was trying to convert the "oyo.pdf" file using following command and getting the following error.
Looking the support.

 invoice2data oyo.pdf

Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 9, in <module>
    load_entry_point('invoice2data==0.2.101', 'console_scripts', 'invoice2data')()
  File "/home/mj/pdf_to_text/invoice2data/invoice2data/main.py", line 158, in main
    templates += read_templates()
  File "/home/mj/pdf_to_text/invoice2data/invoice2data/extract/loader.py", line 90, in read_templates
    tpl = ordered_load(template_file.read())
  File "/home/mj/pdf_to_text/invoice2data/invoice2data/extract/loader.py", line 40, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 46

**Comment by m3nu** [comment]
Unicode issue with French accents. Best to use Python 3. Python 2 is nearing EOL.

**Comment by m3nu** [comment]
Great. If you share your file I can also test it here. Generally the sample files are tested before every update and I suspect this is unique to your setup. Closing this issue for now. Feel free to reopen it if new info emerges.
