### ISSUE TITLE
Error parsing YAML template

### ISSUE THREAD

**Issue by davdigioia** [invoice-x/invoice2data#193]
I got the following error just running the example

'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 46

**Comment by m3nu** [comment]
You probably have a special non-printing char in your template that YAML refuses to read.

**Comment by davdigioia** [comment]
I just tried to run the example: FlipkartInvoice.pdf :(

**Comment by m3nu** [comment]
That's odd. What's your setup? OS? Python version?

**Comment by davdigioia** [comment]
Anaconda on Ubuntu. Python 3.6

**Comment by dnyg** [comment]
I'm having the same issue.

The command `invoice2data invoice1.pdf` gives me the output

```
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 11, in <module>
    load_entry_point('invoice2data==0.3.3', 'console_scripts', 'invoice2data')()
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/main.py", line 191, in main
    templates += read_templates()
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/extract/loader.py", line 88, in read_templates
    tpl = ordered_load(template_file.read())
  File "/usr/local/lib/python2.7/dist-packages/invoice2data/extract/loader.py", line 36, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 46
```

Operating system is Debian 9 - python version 2.7.16

**Comment by m3nu** [comment]
Looks like someone used a non-printable char in a template, something that's not supported by YAML.

Probably related to [this SO question](https://stackoverflow.com/questions/45871058/confronting-unacceptable-character-x0095-special-characters-are-not-allowed-i). Does this happen on Python3?

If yes, we should either strip those non-printable unicode chars before parsing or remove them from the template and make sure they're not added again.

But usually the tests should catch something like this. Since all templates are parsed multiple times during testing.

**Comment by dnyg** [comment]
Very weird issue.

I reinstalled python (`sudo apt remove python` followed by `sudo apt install python`) and it suddenly works again (although my version is the same as before).

**Comment by m3nu** [comment]
Glad to hear. Closing this then.

There is a folder in a Python installation that has some encoding-related files. I once had a similar issue due to permission issues related to those files. Maybe that was your issue too.

**Comment by bazatalla** [comment]
Having the exact same issue. I can't successfully execute `sudo apt remove python` as it breaks dependencies... Any other workaround?

**Comment by m3nu** [comment]
Removing Python is not a good idea. Would recommend to use a venv or user-install instead.

**Comment by darknd** [comment]
The same issue here.

> invoice2data --input-reader gvision --template-folder /home/ubuntu/output/wwwroot/ocr/template/ file.pdf

Traceback (most recent call last):

File "/usr/local/bin/invoice2data", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/invoice2data/main.py", line 194, in main
templates += read_templates(os.path.abspath(args.template_folder))
File "/usr/local/lib/python3.5/dist-packages/invoice2data/extract/loader.py", line 88, in read_templates
tpl = ordered_load(template_file.read())
File "/usr/local/lib/python3.5/dist-packages/invoice2data/extract/loader.py", line 36, in ordered_load
return yaml.load(stream, OrderedLoader)
File "/usr/local/lib/python3.5/dist-packages/yaml/init.py", line 112, in load
loader = Loader(stream)
File "/usr/local/lib/python3.5/dist-packages/yaml/loader.py", line 44, in init
Reader.init(self, stream)
File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 74, in init
self.check_printable(stream)
File "/usr/local/lib/python3.5/dist-packages/yaml/reader.py", line 144, in check_printable
'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0091: special characters are not allowed
in "", position 14

My python version is 3.5.2, running in Ubuntu 16.04.3 LTS.
The gvision global var is setted too.

Any idea? In my local environment (Debian 9 and Python 2.7.16) is working great.

Thank you very much for your time,

**Comment by nemiah** [comment]
I just had the same issue. The "problem" is the €-sign :exclamation: :confused: 
I removed the lines 148 and 149 from `/usr/local/lib/python2.7/dist-packages/yaml/reader.py` and it seems to work for now :blush:
