### ISSUE TITLE
No template for Invoice/*******.pdf False

### ISSUE THREAD

**Issue by NayanMogra** [invoice-x/invoice2data#340]
Hi, I created a template for my pdf, and when I try to run that it is again showing this no template found,
Only QualityHosting invoice is working other invoices are having the same issue though I am creating templates

**Comment by Animesh-CSE** [comment]
Same Issue hare also

**Comment by NayanMogra** [comment]
@Animesh-CSE  
I found the solution add this code in your py file 
import logging.config 
import logging 
logging.basicConfig(level=logging.DEBUG) logging.basicConfig()

And then it will display all the pdf data 
After that just compare that issuer name you wrote is same as that in terminal

**Comment by Animesh-CSE** [comment]
@NayanMogra  Thank You
Now come another issues.Hare it is-

**Traceback (most recent call last):
  File "G:\project\project.py", line 6, in <module>
    result = extract_data('invoice/MyFlipkart.pdf',templates=templates)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\main.py", line 93, in extract_data
    return t.extract(optimized_str)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\invoice_template.py", line 178, in extract
    output[k] = self.parse_date(res_find[0])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\invoice_template.py", line 113, in parse_date
    value, date_formats=self.options['date_formats'], languages=self.options['languages']
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\date.py", line 412, in get_date_data
    raise TypeError('Input type must be str')
TypeError: Input type must be str**

**Comment by RossK1** [comment]
Can you share your template here, please?

**Comment by NayanMogra** [comment]
@Animesh-CSE  yes please share your template

**Comment by Animesh-CSE** [comment]
@RossK1 
@NayanMogra 

# -*- coding: utf-8 -*-
issuer: Flipkart
keywords:
- Flipkart
- Shreyash Retail
- OD
fields:
 date: Invoice Date:\s+(\d{1,2})\-(\d{1,2})\-(\d{2,4})
 amount: Grand Total\s+\₹\s(\d+\.\d{2})
 invoice_number: Invoice Number\s+\#\s(\w{4,7}\d{8,12})
options:
 remove_whitespace: false
 currency: INR
 date_formats:
     - '%d/%m/%Y'
 languages:
     - en

**Comment by Animesh-CSE** [comment]
yml file not supported hare ,thats why i send the code only. This template for recent Flipkart invoices.

**Comment by NayanMogra** [comment]
What I can understand through your template there is some indentation error 
You had fields inside keywords 
You can upload template on GitHub and share link here
 will check and help you then properly

**Comment by RossK1** [comment]
YML is indentation sensitive. I can't tell from that code what your indentation is like. Can you please correct it to be representative?

**Comment by Animesh-CSE** [comment]
@NayanMogra 
@RossK1 
[MyFlipkart.txt](https://github.com/invoice-x/invoice2data/files/6577484/MyFlipkart.txt)

**Comment by RossK1** [comment]
Try remove the date formats option and see if it works and what the dates come out as.

**Comment by NayanMogra** [comment]
You have indentation issue in keyword as well as fields too 
Use tab instead of single space,
Keywords
    - Flipkart 
Do like this

**Comment by Animesh-CSE** [comment]
@NayanMogra  as i paste copying code hare thats why its repesentation are mismached.But in actual code its not.

**Comment by Animesh-CSE** [comment]
@NayanMogra  as i paste copying code hare thats why its repesentation are mismached.But in actual code its not.

![Uploading Screenshot (8).png…]()

**Comment by NayanMogra** [comment]
Also other issue what I can find out is there is no ':' in number and total

**Comment by Animesh-CSE** [comment]
@RossK1  i tried by removing the date but then its showing regex for amount field not matching . But i already check  from regex on regex101 site, its matching.

**Comment by Animesh-CSE** [comment]
@NayanMogra but without ':' ,regex not matching

**Comment by NayanMogra** [comment]
Cant able to open your screenshot 
But two things you can see if,
1. Check indentation of the plugin Keywords
2. though it is not mentioned anywhere try this out:- Move Field plugin above Keyword and check this out

**Comment by Animesh-CSE** [comment]
After using tab this showing-

Traceback (most recent call last):
  File "G:\project\project.py", line 4, in <module>
    templates = read_templates('template/')
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\loader.py", line 88, in read_templates
    tpl = ordered_load(template_file.read())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\loader.py", line 36, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 4, column 1:
    	- Flipkart
    ^

**Comment by Animesh-CSE** [comment]
> Cant able to open your screenshot
> But two things you can see if,
> 
> 1. Check indentation of the plugin Keywords
> 2. though it is not mentioned anywhere try this out:- Move Field plugin above Keyword and check this out
Ok @NayanMogra

**Comment by Animesh-CSE** [comment]
@NayanMogra 
After moving field plag in above keyword-

Traceback (most recent call last):
  File "G:\project\project.py", line 4, in <module>
    templates = read_templates('template/')
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\loader.py", line 88, in read_templates
    tpl = ordered_load(template_file.read())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\loader.py", line 36, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 4, column 1:
    	date: Invoice Date:\s+(\d{1,2}) ... 
    ^
>>>

**Comment by Animesh-CSE** [comment]
@NayanMogra 
![Screenshot (9)](https://user-images.githubusercontent.com/85177735/120354841-6d984e80-c320-11eb-9151-dac236cb424d.png)

**Comment by NayanMogra** [comment]
in regex whenever you get a special character try using \w or \w+ 
According to my understandings 
date: Invoice Date:\s+(\d{1,2})
there are two colons and that might be giving you token issue

**Comment by Animesh-CSE** [comment]
> in regex whenever you get a special character try using \w or \w+
> According to my understandings
> date: Invoice Date:\s+(\d{1,2})
> there are two colons and that might be giving you token issue

i tried to use \w for special character but its not matching.

**Comment by NayanMogra** [comment]
capital W not small

**Comment by Animesh-CSE** [comment]
ok i replaced special character with '\W' but nothing happen, same error

**Comment by NayanMogra** [comment]
Share SS again

**Comment by Animesh-CSE** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/85177735/120357240-d8e32000-c322-11eb-8e2b-913a8c905a42.png)

**Comment by NayanMogra** [comment]
I didn't see any changes in your file it is, the same as before
Date : Invoice\s+Date\s+\W\s+..... do it like this and also instead of using - use \W in date that will also be good

**Comment by Animesh-CSE** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/85177735/120357800-74749080-c323-11eb-8f99-19ca1e37fd90.png)

**Comment by Animesh-CSE** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/85177735/120358543-362ba100-c324-11eb-9851-92483c895028.png)

**Comment by Animesh-CSE** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/85177735/120358609-4e032500-c324-11eb-9410-a4a96687e229.png)

**Comment by Animesh-CSE** [comment]
help me for regex of 
Invoice Date: 18-02-2021

**Comment by NayanMogra** [comment]
Invoice\s+Date\W\s+\d{1,2}\W\d{1,2}\W\d{2,4}

check this out

**Comment by rmilecki** [comment]
```
Invoice Date:\s+(\d{1,2})\-(\d{1,2})\-(\d{2,4})
```
This is the problem. That regex has **three** matching groups. It means `re.findall` returns an array with tuple of **three** strings.

```
Invoice\s+Date\W\s+\d{1,2}\W\d{1,2}\W\d{2,4}
```
This regex doesn't have any matching group, so the whole match will be treated as a date. Depending on how smart data parser is, it may success or not.

Just use a single matching group like:
```
Invoice Date:\s+(\d{1,2}-\d{1,2}-\d{2,4})
```
