### ISSUE TITLE
TypeError: Input type must be str

### ISSUE THREAD

**Issue by Animesh-CSE** [invoice-x/invoice2data#347]
```
Traceback (most recent call last):
  File "G:\project\project.py", line 6, in <module>
    result = extract_data('invoice/MyFlipkart.pdf',templates=templates)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\main.py", line 93, in extract_data
    return t.extract(optimized_str)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\invoice_template.py", line 178, in extract
    output[k] = self.parse_date(res_find[0])
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\invoice2data\extract\invoice_template.py", line 113, in parse_date
    value, date_formats=self.options['date_formats'], languages=self.options['languages']
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateparser\date.py", line 412, in get_date_data
    raise TypeError('Input type must be str')
TypeError: Input type must be str
```

**Comment by Animesh-CSE** [comment]
[MyFlipkart.txt](https://github.com/invoice-x/invoice2data/files/6577479/MyFlipkart.txt)

**Comment by rmilecki** [comment]
```
date: Invoice Date:\s+(\d{1,2})\-(\d{1,2})\-(\d{2,4})
```
This regex is invalid as it captures **three** numbers. It results in an array of **three** entries. It must be a single string.

Fix your regex to use **one** capture only (one opening bracket and one closing bracket).
