### ISSUE TITLE
Output filename and Move function not working [AttributeError]

### ISSUE THREAD

**Issue by bosd** [invoice-x/invoice2data#374]
Running invoice2data with the `--move` option on  python3 throws the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 10, in <module>
    sys.exit(main())
  File "/home/emiel/.local/lib/python3.7/site-packages/invoice2data/main.py", line 227, in main
    date=res["date"].strftime("%Y-%m-%d"),
AttributeError: 'list' object has no attribute 'strftime'
```

I have noticed that in main.py datetime is not imported.
adding the import did not solve the prolem.

**Comment by bosd** [comment]
Also noticed that by default the output extension gets forced to pdf. Even when processing scanned image files.
