### ISSUE TITLE
TypeError: first argument must be string or compiled pattern

### ISSUE THREAD

**Issue by ledahosn** [invoice-x/invoice2data#432]
Hello, I'm trying my best to understand invoice2data to get my Results. But I am not able to do so.

DEBUG Log:
`DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 142 template files
Traceback (most recent call last):
  File "/usr/local/bin/invoice2data", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/invoice2data/main.py", line 210, in main
    res = extract_data(f.name, templates=templates, input_module=input_module)
  File "/usr/local/lib/python3.9/dist-packages/invoice2data/main.py", line 92, in extract_data
    if t.matches_input(optimized_str):
  File "/usr/local/lib/python3.9/dist-packages/invoice2data/extract/invoice_template.py", line 106, in matches_input
    if all([re.search(keyword, optimized_str) for keyword in self["keywords"]]):
  File "/usr/local/lib/python3.9/dist-packages/invoice2data/extract/invoice_template.py", line 106, in <listcomp>
    if all([re.search(keyword, optimized_str) for keyword in self["keywords"]]):
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 303, in _compile
    raise TypeError("first argument must be string or compiled pattern")`

Template File
`issuer: 'fonira Telekom GmbH'
keywords:
- fonira
- 2905725
fields:
  invoice_number: Rechnungsnummer\:\s+(.*-.{3,5})
options:
  decimal_separator: ','`

**Comment by rmilecki** [comment]
Please try with
```
keywords:
  - fonira
  - 2905725
```
(whitespaces matter in YAML files)

**Comment by ledahosn** [comment]
`keywords:
  - fonira
  - '2905725'
`

Solved it to Escape the Integer
