### ISSUE TITLE
Error "AttributeError: 'list' object has no attribute 'strftime'" when using "_date" in field name

### ISSUE THREAD

**Issue by iedev1** [invoice-x/invoice2data#441]
When defining fields for extraction if the field name is either prefixed with `date_` or suffixed with `_date`, invoice2data errors with an `AttributeError`.

This happens regardless of setting the `type` property to date/string.

If I simply rename the field, the extraction/capturing works as expected.

Here is the relevant line from the config:

```
fields:
    # [...]
    deposit_date:
        parser: regex
        regex: 
          - Deposit Date: (\d{2}\/\d{2}\/\d{4})
        type: date
```

Here is the error:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/invoice2data", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/invoice2data/main.py", line 231, in main
    output_module.write_to_file(output, args.output_name, args.output_date_format)
  File "/opt/homebrew/lib/python3.10/site-packages/invoice2data/output/to_json.py", line 46, in write_to_file
    line[k] = v.strftime(date_format)
AttributeError: 'list' object has no attribute 'strftime'
```

**Comment by bosd** [comment]
A couple of minutes after this ticket was openend an new version has been published on pypi.
Which version are you using??
Could you update to the latest version and check if it is resolved?

**Comment by rmilecki** [comment]
I tried to reproduce this but I actually got yet another problem:
```
Traceback (most recent call last):
  File "/home/foo/.local/bin/invoice2data", line 11, in <module>
    load_entry_point('invoice2data', 'console_scripts', 'invoice2data')()
  File "/home/foo/invoice2data/src/invoice2data/main.py", line 224, in main
    res = extract_data(f.name, templates=templates, input_module=input_module)
  File "/home/foo/invoice2data/src/invoice2data/main.py", line 108, in extract_data
    return t.extract(optimized_str, invoicefile, input_module)
  File "/home/foo/invoice2data/src/invoice2data/extract/invoice_template.py", line 216, in extract
    value = parser.parse(self, k, v, optimized_str_for_parser)
  File "/home/foo/invoice2data/src/invoice2data/extract/parsers/regex.py", line 33, in parse
    matches = re.findall(regex, content)
  File "/usr/lib64/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib64/python3.6/re.py", line 289, in _compile
    p, loc = _cache[type(pattern), pattern, flags]
TypeError: unhashable type: 'collections.OrderedDict'
```
It's interesting. On my system parsing your template results in
```
          - Deposit Date: (\d{2}\/\d{2}\/\d{4})
```
being parsed as `collections.OrderedDict` instead of `str`.

I solved that by simply adding quotes to yout template. I'll debug JSON thing later today.
