### ISSUE TITLE
Latest Release v0.4.3 causes a lot of errors

### ISSUE THREAD

**Issue by gdgellatly** [invoice-x/invoice2data#504]
It seems related to the format / logging with a Nonetype error. But it is weird, it is like it is overwriting main python modules as invoice2data is causing the error in places it isn;t even used.

```
File "/usr/local/lib/python3.8/site-packages/invoice2data/main.py", line 80, in format
odoo_1        |     record.prefix = self.LOG_LEVEL_COLOR.get(record.levelname.upper()).get("prefix")
```

When loading a stock screen

**Comment by gdgellatly** [comment]
Fuller Traceback, but essentially every log request with invoice2data 0.4.3 installed, causes an error like this. 

```
odoo_1        | --- Logging error ---
odoo_1        | Traceback (most recent call last):
odoo_1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
odoo_1        |     msg = self.format(record)
odoo_1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
odoo_1        |     return fmt.format(record)
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/invoice2data/main.py", line 80, in format
odoo_1        |     record.prefix = self.LOG_LEVEL_COLOR.get(record.levelname.upper()).get("prefix")
odoo_1        | AttributeError: 'NoneType' object has no attribute 'get'
odoo_1        | Call stack:
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
odoo_1        |     return handle(*args_tuple)
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1532, in handle
odoo_1        |     handler.handle()
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 457, in handle
odoo_1        |     result = self.handle_one_request()
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 678, in handle_one_request
odoo_1        |     self.handle_one_response()
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 995, in handle_one_response
odoo_1        |     self.log_request()
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 880, in log_request
odoo_1        |     self.server.log.write(self.format_request() + '\n')
odoo_1        |   File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1181, in write
odoo_1        |     self._logger.log(self._level, msg)
odoo_1        | Message: '172.16.24.28 - - [2023-04-02 01:18:46] "POST /longpolling/poll HTTP/1.1" 200 387 50.032276'
odoo_1        | Arguments: ()
```

**Comment by bosd** [comment]
Yeah, j noticed it, only when using it as a lib. CLI seems fine.

It is related to the initiation of the logger.
Didn't have time to look further into it..
